[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'sett currencies SettCurrencies pallet'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = "stp258"
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.4.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.1", default-features = false, features = [ "derive"] }
fetch-price = { default-features = false, package = 'fetch-price', version = '0.4.1', git = 'https://github.com/Setheum-Labs/fetch-price' }
sp-std = { default-features = false, optional = true, version = '3.0.0' }
serde = { version = "1.0.123", optional = true }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
orml-traits = { default-features = false, version = '0.4.0' }
orml-utilities = { default-features = false, version = '0.4.0' }
num-rational = { default-features = false, version = '0.3.2' }
num-traits = { version = "0.2.14", default-features = false }
fixed = { default-features = false, version = '1.6.0' }
sp-runtime = { default-features = false, optional = true, version = '3.0.0' }

[dev-dependencies]
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
orml-tokens = { default-features = false, version = '0.4.0' }
pallet-assets = { default-features = false, version = '3.0.0' }
pallet-balances = "3.0.0"

[features]
default = ['std']
std = [
    'codec/std',
    "fetch-price/std",
    "fixed/std",
    'frame-support/std',
    'frame-system/std',
    "num-rational/std",
	"num-traits/std",
	"orml-traits/std",
    "orml-tokens/std",
    'orml-utilities/std',
	"serde/std",
    "sp-runtime/std",
	"sp-io/std",
    "sp-std",
]
