name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      SCCACHE_CACHE_SIZE: "50G"
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2021-02-17
        target: wasm32-unknown-unknown
        default: true
    - name: Build
      run: cargo build --verbose
    - name: Cargo unleash check
      run: cargo unleash checkout --verbose
    - name: Run tests
      run: CARGO test-all --verbose
